kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pod-killing
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app: adservice
  mode: all
  action: pod-kill
